# termfeed module: standalone test & lua binding recipes
# CWD = mods/termfeed (just -f sets working dir to justfile dir)
# run from repo root: just -f mods/termfeed/justfile [test|cov|lua|...]

import '../../build.just'


test *tests='': (dbg-run "termfeed_test" "-I. -I../.." tests)

cov: (cov-run "termfeed_test" "-I. -I../..") (cov-show "termfeed.h")

lines: (cov-lines "termfeed.h")

unbranched: (cov-unbranched "termfeed.h")

clean: clean-gcda
    rm -f termfeed_test *.gcda *.gcno

lua-build:
    mkdir -p ../../build/lua55 ../../build/luajit
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUA55_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o ../../build/lua55/termfeed.so termfeed.c
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUAJIT_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o ../../build/luajit/termfeed.so termfeed.c

lua *t='': lua-build
    lua ../../tests/lua/tf_test.lua {{ t }}
    luajit ../../tests/lua/tf_test.lua {{ t }}

lua-cov: clean-gcda
    rm -f ../../build/*/*.gcda ../../build/*/*.gcno
    mkdir -p ../../build/lua55 ../../build/luajit
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUA55_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o ../../build/lua55/termfeed.so termfeed.c
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUAJIT_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o ../../build/luajit/termfeed.so termfeed.c
    lua ../../tests/lua/tf_test.lua && luajit ../../tests/lua/tf_test.lua
    lcov --capture --directory ../../build --base-directory . --rc branch_coverage=1 --output-file lua_coverage.info --ignore-errors mismatch
    lcov --extract lua_coverage.info '*/termfeed.c' --rc branch_coverage=1 --output-file lcov.info
    @echo ""
    @echo "=== termfeed.c coverage ==="
    lcov --list --rc branch_coverage=1 lcov.info

lua-lines: (cov-lines "termfeed.c")
