-- tests/gen_entries.lua — generate entries table + main for a test source.
--
-- Scans TEST(name) functions (one per line, `^TEST(name)`) and writes a
-- .gen.inc file: test_entry array + main.  The test source includes it:
--   #include "foo.gen.inc"
-- Build artifact, gitignored; regenerated by just before compiling.
--
-- usage: lua tests/gen_entries.lua <src.c> <out.inc> [win32]
-- Optional third arg (win32) collects tests from #else branches of
-- `#if !defined(_WIN32)` blocks and skips the POSIX branch, matching
-- what the C preprocessor does on Windows.

local src, out, win32flag = arg[1], arg[2], arg[3] == "win32"
if not src or not out then
    io.stderr:write("usage: lua tests/gen_entries.lua <src.c> <out.inc> [win32]\n")
    os.exit(1)
end

-- Normalize backslashes: Windows paths would leak '\x' sequences into
-- the generated banner string (unknown escape -> compiler warning).
src = src:gsub("\\", "/")
out = out:gsub("\\", "/")

local base = src:match("([^/]+)%.c$") or src
local lib = base:match("^([a-z]+)_test") or base
local tag = base:match("^[a-z]+_test_(.+)$")
local banner = tag and ("[" .. lib .. " " .. tag .. "]") or ("[" .. lib .. "]")
local f = assert(io.open(src, "r"))
local names = {}

-- Minimal conditional compilation tracker: only `#if` lines mentioning
-- defined(_WIN32) are evaluated (win32 vs not); anything else counts
-- as true.  Handles #else flips and nested blocks.
local depth, skip = 0, 0
local function iftrue(line)
    if line:find("!defined%(_WIN32%)") then return not win32flag end
    if line:find("defined%(_WIN32%)") then return win32flag end
    return true
end
for line in f:lines() do
    local dir = line:match("^#(%w+)")
    if dir == "if" then
        depth = depth + 1
        if not iftrue(line) then skip = skip + 1 end
    elseif dir == "endif" then
        if skip > 0 then skip = skip - 1 end
        depth = depth - 1
    elseif dir == "else" then
        if skip > 0 then
            skip = skip - 1
        elseif depth > 0 then
            skip = skip + 1
        end
    elseif skip == 0 then
        local name = line:match("^%s*TEST%(([%w_]+)%)")
        if name then names[#names + 1] = name end
    end
end
f:close()

local o = assert(io.open(out, "w"))
o:write("/* generated by tests/gen_entries.lua from " .. src .. " */\n")
o:write("/* do not edit */\n")
o:write("static const test_entry test_entries[] = {\n")
for _, n in ipairs(names) do
    o:write("    {\"" .. n .. "\", test_" .. n .. "},\n")
end
o:write("    {NULL, NULL}\n};\n")
o:write("\nint main(int argc, char *argv[]) {\n")
o:write("    return test_run(\"" .. banner .. "\", test_entries, argc, argv);\n")
o:write("}\n")
o:close()
