# lua bindings: build, test, coverage. CWD = lua/ (just lua/<recipe> sets it)
# run from repo root: just lua/<name> | just lua/<name>-cov | just lua/<name>-lines | just lua/clean

import '../build.just'

INCS := "-I. -I.."

build mod:
    mkdir -p luajit
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUA55_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o {{ mod }}.so {{ mod }}.c
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUAJIT_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o luajit/{{ mod }}.so {{ mod }}.c

run t *args='':
    lua tests/{{ t }}.lua {{ args }}
    luajit tests/{{ t }}.lua {{ args }}

pt *args='': (build "piecetab") (run "piecetab_test" args)
cg *args='': (build "cellgrid") (run "cellgrid_test" args)
tf *args='': (build "termfeed") (run "termfeed_test" args)
yyjson *args='': (build "yyjson") (run "yyjson_test" args)
jsonrpc *args='': (build "yyjson") (run "jsonrpc_test" args)
lspio *args='': (build "yyjson") (run "lspio_test" args)
lspclient *args='': (build "yyjson") (run "lspclient_test" args)
# editor demo needs lua-utf8 rock (PUC Lua only)
ed *args='': (build "piecetab") (build "cellgrid") (build "termfeed")
    lua tests/editor_test.lua {{ args }}

TS_INC := "-I/opt/homebrew/include"
TS_LIB := "-L/opt/homebrew/lib -ltree-sitter"

ts-grammars *langs='c lua':
    ../misc/fetch_grammars.sh {{langs}}

build-ts: ts-grammars
    mkdir -p luajit
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUA55_INC }} {{ TS_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o treesitter.so treesitter.c {{ TS_LIB }}
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUAJIT_INC }} {{ TS_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o luajit/treesitter.so treesitter.c {{ TS_LIB }}

ts *args='': (build-ts) (run "treesitter_test" args)

cov mod t:
    rm -f *.gcda luajit/*.gcda
    mkdir -p luajit
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUA55_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o {{ mod }}.so {{ mod }}.c
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUAJIT_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o luajit/{{ mod }}.so {{ mod }}.c
    lua tests/{{ t }}.lua && luajit tests/{{ t }}.lua
    lcov --capture --directory . --base-directory . --rc branch_coverage=1 --output-file lua_coverage.info --ignore-errors mismatch
    lcov --extract lua_coverage.info '*/{{ mod }}.c' --rc branch_coverage=1 --output-file lcov.info
    @echo ""
    @echo "=== {{ mod }}.c coverage ==="
    lcov --list --rc branch_coverage=1 lcov.info

pt-cov: (cov "piecetab" "piecetab_test")
cg-cov: (cov "cellgrid" "cellgrid_test")
tf-cov: (cov "termfeed" "termfeed_test")

yyjson-cov:
    rm -f *.gcda luajit/*.gcda
    mkdir -p luajit
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUA55_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o yyjson.so yyjson.c
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUAJIT_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o luajit/yyjson.so yyjson.c
    lua tests/yyjson_test.lua && luajit tests/yyjson_test.lua
    lcov --capture --directory . --base-directory . --rc branch_coverage=1 --output-file lua_coverage.info --ignore-errors mismatch,inconsistent,unsupported
    lcov --extract lua_coverage.info '*/yyjson.c' --rc branch_coverage=1 --output-file lcov.info --ignore-errors mismatch,inconsistent,unsupported
    lcov --remove lcov.info '*/yyjson/yyjson.c' --rc branch_coverage=1 --output-file lcov.info --ignore-errors mismatch,inconsistent,unsupported
    @echo ""
    @echo "=== yyjson.c coverage ==="
    lcov --list --rc branch_coverage=1 lcov.info

ts-cov:
    rm -f *.gcda luajit/*.gcda
    mkdir -p luajit
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUA55_INC }} {{ TS_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o treesitter.so treesitter.c {{ TS_LIB }}
    {{ CC }} {{ LUAFLAGS }} {{ INCS }} {{ LUAJIT_INC }} {{ TS_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o luajit/treesitter.so treesitter.c {{ TS_LIB }}
    lua tests/treesitter_test.lua && luajit tests/treesitter_test.lua
    lcov --capture --directory . --base-directory . --rc branch_coverage=1 --output-file lua_coverage.info --ignore-errors mismatch
    lcov --extract lua_coverage.info '*/treesitter.c' --rc branch_coverage=1 --output-file lcov.info
    @echo ""
    @echo "=== treesitter.c coverage ==="
    lcov --list --rc branch_coverage=1 lcov.info

lines mod:
    @awk '/^DA:/ && /,0$/ {gsub(/DA:|,0/,""); print $0}' lcov.info \
    | sort -n | while read ln; do echo "L$ln: $(sed -n ${ln}p {{ mod }}.c)"; done

pt-lines: (lines "piecetab")
cg-lines: (lines "cellgrid")
tf-lines: (lines "termfeed")
ts-lines: (lines "treesitter")

clean: clean-gcda
    rm -f *.so luajit/*.so *.gcda luajit/*.gcda lua_coverage.info lcov.info
