-- tests/gen_entries.lua — generate entries table + main for a test source.
--
-- Scans TEST(name) functions (one per line, `^TEST(name)`) and writes a
-- .gen.inc file: test_entry array + main.  The test source includes it:
--   #include "foo.gen.inc"
-- Build artifact, gitignored; regenerated by just before compiling.
--
-- usage: lua tests/gen_entries.lua <src.c> <out.inc>

local src, out = arg[1], arg[2]
if not src or not out then
    io.stderr:write("usage: lua tests/gen_entries.lua <src.c> <out.inc>\n")
    os.exit(1)
end

local base = src:match("([^/]+)%.c$") or src
local lib = base:match("^([a-z]+)_test") or base
local tag = base:match("^[a-z]+_test_(.+)$")
local banner = tag and ("[" .. lib .. " " .. tag .. "]") or ("[" .. lib .. "]")
local f = assert(io.open(src, "r"))
local names = {}
for line in f:lines() do
    local name = line:match("^%s*TEST%(([%w_]+)%)")
    if name then names[#names + 1] = name end
end
f:close()

local o = assert(io.open(out, "w"))
o:write("/* generated by tests/gen_entries.lua from " .. src .. " */\n")
o:write("/* do not edit */\n")
o:write("static const test_entry test_entries[] = {\n")
for _, n in ipairs(names) do
    o:write("    {\"" .. n .. "\", test_" .. n .. "},\n")
end
o:write("    {NULL, NULL}\n};\n")
o:write("\nint main(int argc, char *argv[]) {\n")
o:write("    return test_run(\"" .. banner .. "\", test_entries, argc, argv);\n")
o:write("}\n")
o:close()
