import '../build.just'
MODULE := "tests"

# C tests: one runner per lib, parametrized. Lua side lives in lua/justfile.

INCS := "-I."

# run all C test runners
[default]
all: root lc4 lc8 pt sp4 sp8 ut cg tf tm

# linecache fanout-4 tests (ASan/UBSan)
lc4 *args='': root (c-dbg-run "linecache_test_fanout4" INCS args)
# linecache fanout-8 tests (ASan/UBSan)
lc8 *args='': root (c-dbg-run "linecache_test_fanout8" INCS args)
# linecache tests on both fanout variants
lc *args='': root (c-dbg-run "linecache_test_fanout4" INCS "?" + args) (c-dbg-run "linecache_test_fanout8" INCS "?" + args)
# piecetab tests (ASan/UBSan)
pt *args='': root (c-dbg-run "piecetab_test_fanout4" INCS args)
# undotree tests (ASan/UBSan)
ut *args='': root (c-dbg-run "undotree_test" INCS args)
# cellgrid tests (ASan/UBSan)
cg *args='': root (c-dbg-run "cellgrid_test" INCS args)
# termfeed tests (ASan/UBSan)
tf *args='': root (c-dbg-run "termfeed_test" INCS args)
# textmatch tests (ASan/UBSan)
tm *args='': root tm-check (c-dbg-run "textmatch_test" INCS args)

[private]
tm-check:
    lua "$ROOT/misc/check_textmatch.lua" "$ROOT/textmatch.h"
# spantree fanout-4 tests (ASan/UBSan)
sp4 *args='': root (c-dbg-run "spantree_test_fanout4" INCS args)
# spantree fanout-8 tests (ASan/UBSan)
sp8 *args='': root (c-dbg-run "spantree_test_fanout8" INCS args)
# spantree tests on both fanout variants
sp *args='': root (c-dbg-run "spantree_test_fanout4" INCS "?" + args) (c-dbg-run "spantree_test_fanout8" INCS "?" + args)

# coverage: build and run all C tests, then report combined coverage
cov: root clean-gcda (c-cov-run "linecache_test_fanout4" INCS) (c-cov-run "linecache_test_fanout8" INCS) (c-cov-run "piecetab_test_fanout4" INCS) (c-cov-run "undotree_test" INCS) (c-cov-run "cellgrid_test" INCS) (c-cov-run "termfeed_test" INCS) (c-cov-run "spantree_test_fanout4" INCS) (c-cov-run "textmatch_test" INCS) (cov-show ".." "piecetab.h linecache.h undotree.h cellgrid.h termfeed.h spantree.h textmatch.h")

# linecache coverage
lc-cov: root clean-gcda (c-cov-run "linecache_test_fanout4" INCS) (c-cov-run "linecache_test_fanout8" INCS) (cov-show ".." "linecache.h")
# piecetab coverage
pt-cov: root clean-gcda (c-cov-run "piecetab_test_fanout4" INCS) (cov-show ".." "piecetab.h")
# undotree coverage
ut-cov: root clean-gcda (c-cov-run "undotree_test" INCS) (cov-show ".." "undotree.h")
# cellgrid coverage
cg-cov: root clean-gcda (c-cov-run "cellgrid_test" INCS) (cov-show ".." "cellgrid.h")
# termfeed coverage
tf-cov: root clean-gcda (c-cov-run "termfeed_test" INCS) (cov-show ".." "termfeed.h")
# textmatch coverage
tm-cov: root clean-gcda (c-cov-run "textmatch_test" INCS) (cov-show ".." "textmatch.h")
# spantree coverage
sp-cov: root clean-gcda (c-cov-run "spantree_test_fanout4" INCS) (c-cov-run "spantree_test_fanout8" INCS) (cov-show ".." "spantree.h")

# linecache uncovered lines
lc-lines: (cov-lines "linecache.h" "../lcov.info")
# piecetab uncovered lines
pt-lines: (cov-lines "piecetab.h" "../lcov.info")
# undotree uncovered lines
ut-lines: (cov-lines "undotree.h" "../lcov.info")
# cellgrid uncovered lines
cg-lines: (cov-lines "cellgrid.h" "../lcov.info")
# termfeed uncovered lines
tf-lines: (cov-lines "termfeed.h" "../lcov.info")
# textmatch uncovered lines
tm-lines: (cov-lines "textmatch.h" "../lcov.info")
# spantree uncovered lines
sp-lines: (cov-lines "spantree.h" "../lcov.info")

# linecache uncovered branches
lc-unbranched: (cov-unbranched "linecache.h" "../lcov.info")
# piecetab uncovered branches
pt-unbranched: (cov-unbranched "piecetab.h" "../lcov.info")
# undotree uncovered branches
ut-unbranched: (cov-unbranched "undotree.h" "../lcov.info")
# cellgrid uncovered branches
cg-unbranched: (cov-unbranched "cellgrid.h" "../lcov.info")
# termfeed uncovered branches
tf-unbranched: (cov-unbranched "termfeed.h" "../lcov.info")
# textmatch uncovered branches
tm-unbranched: (cov-unbranched "textmatch.h" "../lcov.info")
# spantree uncovered branches
sp-unbranched: (cov-unbranched "spantree.h" "../lcov.info")

# remove C coverage artifacts in this directory
clean-gcda:
    -just rm-gcda "."

# remove generated C test binaries and coverage artifacts
clean: clean-gcda
    -rm -fr *.dSYM
    -rm -f *_test_fanout4 *_test_fanout8 *_test
    -rm -f *.exe *.exp *.lib *.pdb *.gen.inc
