/* tests/tests.h — shared C test utilities, stb style (C89)
 *
 * Test source layout:
 *   #include "tests.h"
 *   TEST(foo) { ... }            -- defines static void test_foo(void)
 *   #include "foo.gen.inc"       -- generated by tests/gen_entries.lua
 *
 * The .gen.inc (entries table + main) is a build artifact regenerated by
 * just before compiling; never edit it.  Asserts abort on failure with
 * file:line; boolean checks use the standard assert().
 */

#ifndef TESTS_H
#define TESTS_H

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define test_log(...) fprintf(stderr, __VA_ARGS__)
#define test_lu(x)    ((unsigned long)(x))

/* TEST(name) — define a test function: static void test_##name(void) */
#define TEST(name) static void test_##name(void)

/* asserteq — abort if (a) != (b), as long */
#define asserteq(a, b)                                                       \
    do {                                                                     \
        long _a = (long)(a), _b = (long)(b);                                 \
        if (_a != _b) {                                                      \
            test_log("FAIL %s:%d: %s == %ld, expected %ld\n", __FILE__,      \
                     __LINE__, #a, _a, _b);                                  \
            abort();                                                         \
        }                                                                    \
    } while (0)

/* assertstreq — abort if strcmp(a, b) != 0 */
#define assertstreq(a, b)                                                    \
    do {                                                                     \
        const char *_sa = (a), *_sb = (b);                                   \
        if (strcmp(_sa, _sb) != 0) {                                         \
            test_log("FAIL %s:%d: '%s' != '%s'\n", __FILE__, __LINE__, _sa,  \
                     _sb);                                                   \
            abort();                                                         \
        }                                                                    \
    } while (0)

/* check — for invariant-checker helpers: log and return 0 on failure */
#define check(e, ...)                                                        \
    do {                                                                     \
        if (!(e)) return test_log(__VA_ARGS__), 0;                           \
    } while (0)

/* ---- allocators ---- */

#if __GNUC__
# define TEST_STATIC static __attribute((unused))
#else
# define TEST_STATIC static
#endif

TEST_STATIC void *test_alloc(void *ud, void *p, size_t osize, size_t nsize) {
    void *np;
    (void)ud, (void)osize;
    if (nsize == 0) return free(p), NULL;
    np = realloc(p, nsize);
    if (!np) abort();
    return np;
}

TEST_STATIC void *oom_alloc(void *ud, void *ptr, size_t osize, size_t nsize) {
    int *cnt = (int *)ud;
    (void)osize;
    if (nsize == 0) {
        free(ptr);
        return NULL;
    }
    if (!cnt || *cnt <= 0) return NULL;
    (*cnt)--;
    return realloc(ptr, nsize);
}

/* counting allocators — track live bytes so tests can assert no leaks */

typedef struct {
    long live;
} Count;

TEST_STATIC void *count_alloc(void *ud, void *ptr, size_t osize, size_t nsize) {
    Count *c = (Count *)ud;
    if (nsize == 0) return c->live -= (long)osize, free(ptr), NULL;
    if (ptr) c->live -= (long)osize;
    ptr = realloc(ptr, nsize);
    if (!ptr) abort();
    return c->live += (long)nsize, ptr;
}

typedef struct {
    long live;
    int  oom;
} OomCount;

TEST_STATIC void *oomcount_alloc(void *ud, void *ptr, size_t osize,
                                 size_t nsize) {
    OomCount *c = (OomCount *)ud;
    if (nsize == 0) return c->live -= (long)osize, free(ptr), NULL;
    if (c->oom <= 0) return NULL;
    c->oom--;
    if (ptr) c->live -= (long)osize;
    ptr = realloc(ptr, nsize);
    if (!ptr) abort();
    return c->live += (long)nsize, ptr;
}

/* ---- runner ---- */

typedef struct {
    const char *name;
    void (*fn)(void);
} test_entry;

/* test_run — no args: run all; args: prefix match, '@' = first only */
int test_run(const char *banner, const test_entry *entries, int argc,
             char *argv[]) {
    int i, j;
    test_log("=== %s ===\n", banner);
    if (argc == 1) {
        const test_entry *e = entries;
        while (e->name) {
            test_log("- %s\n", e->name);
            e->fn();
            test_log("  %s OK\n", e->name);
            ++e;
        }
        test_log("\n%s All tests passed!\n", banner);
        return 0;
    }
    for (i = 1; i < argc; ++i) {
        const char *name = argv[i];
        size_t      len = strlen(name);
        int         found = 0, only = *name == '@';
        if (only) name++, len--;
        for (j = 0; entries[j].name; ++j) {
            if (strlen(entries[j].name) >= len
                && strncmp(name, entries[j].name, len) == 0) {
                test_log("- %s\n", entries[j].name);
                entries[j].fn();
                test_log("  %s OK\n", entries[j].name);
                found = 1;
                if (only) break;
            }
        }
        if (!found) {
            test_log("Unknown test: %s\n", name);
            return 1;
        }
    }
    return 0;
}

#endif /* TESTS_H */
