# cellgrid module: standalone test & lua binding recipes
# CWD = mods/cellgrid (just -f sets working dir to justfile dir)
# run from repo root: just -f mods/cellgrid/justfile [test|cov|lua|...]

import '../../build.just'


test *tests='': (dbg-run "cellgrid_test" "-I. -I../.." tests)

cov: (cov-run "cellgrid_test" "-I. -I../..") (cov-show "cellgrid.h")

lines: (cov-lines "cellgrid.h")

unbranched: (cov-unbranched "cellgrid.h")

clean: clean-gcda
    rm -f cellgrid_test *.gcda *.gcno

lua-build:
    mkdir -p ../../build/lua55 ../../build/luajit
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUA55_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o ../../build/lua55/cellgrid.so cellgrid.c
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUAJIT_INC }} -DNDEBUG -O2 -bundle -undefined dynamic_lookup -o ../../build/luajit/cellgrid.so cellgrid.c

lua *t='': lua-build
    lua ../../tests/lua/cg_test.lua {{ t }}
    luajit ../../tests/lua/cg_test.lua {{ t }}

lua-cov: clean-gcda
    rm -f ../../build/*/*.gcda ../../build/*/*.gcno
    mkdir -p ../../build/lua55 ../../build/luajit
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUA55_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o ../../build/lua55/cellgrid.so cellgrid.c
    {{ CC }} {{ LUAFLAGS }} -I. -I../.. {{ LUAJIT_INC }} --coverage -g -O0 -bundle -undefined dynamic_lookup -o ../../build/luajit/cellgrid.so cellgrid.c
    lua ../../tests/lua/cg_test.lua && luajit ../../tests/lua/cg_test.lua
    lcov --capture --directory ../../build --base-directory . --rc branch_coverage=1 --output-file lua_coverage.info --ignore-errors mismatch
    lcov --extract lua_coverage.info '*/cellgrid.c' --rc branch_coverage=1 --output-file lcov.info
    @echo ""
    @echo "=== cellgrid.c coverage ==="
    lcov --list --rc branch_coverage=1 lcov.info

lua-lines: (cov-lines "cellgrid.c")
